server:
  port: 9999
  servlet:
    session:
      # 让tomcat只能从cookie中获取会话信息
      tracking-modes: COOKIE

spring:
  thymeleaf:
    # 关闭页面缓存，便于开发环境测试
    cache: false
    # 静态资源路径
    prefix: classpath:/templates/
    # 网页资源默认.html结尾
    mode: HTML